services:
  main:
    image: postgres:14
    container_name: postgres-main
    ports:
      - "5438:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - ./master:/var/lib/postgresql/data
      - type: tmpfs 
        target: /dev/shm

  replica_1:
    image: postgres:14
    container_name: postgres-replica
    ports:
      - "5439:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - ./replication:/var/lib/postgresql/data
      - type: tmpfs 
        target: /dev/shm
    depends_on:
      - main
